# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mathew Fraser Robertson
email: MathewFraserRobertson@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 - Data Scientist with a PhD in Astrophysics (check out my [thesis](https://sussex.figshare.com/articles/thesis/Higher_order_lensing_of_the_cosmic_microwave_background/29686667?file=56688578) 👈)
    - I developed new statistical methods to detect subtle trends from complex datasets ([paper](https://iopscience.iop.org/article/10.1088/1475-7516/2023/08/048) 👈)
    - And built an analysis pipeline using terabyte-scale simulations on a super computer ([paper](https://iopscience.iop.org/article/10.1088/1475-7516/2025/02/034) 👈)
 - I have industry experience deploying agile machine learning software for banks in a client-facing role at Featurespace
  - And have significant quantitative data analysis background through several international research internships 🇬🇧 🇩🇪 🇸🇦
twitter_username: username
linkedin_username: "mathew-fraser-robertson"
github_username: "mfrobertson"
orcid: "0009-0003-7176-2475"
search: false
uofg_image: https://images.seeklogo.com/logo-png/14/1/university-of-glasgow-logo-png_seeklogo-145972.png
uofs_image: https://upload.wikimedia.org/wikipedia/commons/3/34/University_of_Sussex_Logo.svg
uofma_image: https://upload.wikimedia.org/wikipedia/commons/4/4f/UMass_Seal_Medium_PMS_202.png
fs_image: https://viterbicareers.usc.edu/wp-content/uploads/2019/11/king-abdullah-university-of-science-and-technology-kaust-logo.png
kaust_image: https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Desy_logo_3c_web.svg/1200px-Desy_logo_3c_web.svg.png
desy_image: https://images.seeklogo.com/logo-png/14/1/university-of-glasgow-logo-png_seeklogo-145972.png

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Mathew Fraser Robertson"
  avatar : "/assets/images/me.jpeg"
  bio    : 'Data Scientist &#124; Astrophysics PhD &#124; Python • SQL • Statistical Modelling'
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/mathew-fraser-robertson"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mfrobertson"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:mathewfraserrobertson@gmail.com"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0009-0003-7176-2475"
    - label: "CV"
      icon: "fas fa-fw fa-file-alt"
      url: "/assets/CV.pdf"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/mathew-fraser-robertson"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mfrobertson"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:mathewfraserrobertson@gmail.com"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0009-0003-7176-2475"
    - label: "CV"
      icon: "fas fa-fw fa-file-alt"
      url: "/assets/CV.pdf"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
